apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tfe-internal-cfg
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfe
    app.kubernetes.io/name: {{ .Release.Name }}-tfe
data:
  MS_INTERNAL_CUSTOMER: "http://{{ .Release.Name }}-tfc-svc.{{ .Release.Namespace }}.svc.cluster.local:8080"
  MS_INTERNAL_PAYMENT: "http://{{ .Release.Name }}-tfp-svc.{{ .Release.Namespace }}.svc.cluster.local:8080"
  MS_INTERNAL_ORDER: "http://{{ .Release.Name }}-tfo-svc.{{ .Release.Namespace }}.svc.cluster.local:8080"
  INSPECT_BEANS: "{{ .Values.env.inspect_beans.enabled }}"
  SERVER_PORT: {{ .Values.service.port | quote }}