totem-food-customer-service:
  replicaCount: 1

  image:
    repository: jeffersoncleyson/totem-food-customer-service
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  loadBalancer:
    totem_food:
      createPublicLB: false

  secrets:
    cognito:
      userPoolId: userPoolId
      clientId: clientId
      clientSecret: clientSecret

  ## https://towardsdatascience.com/how-to-set-up-ingress-controller-in-aws-eks-d745d9107307
  ingress:
    path:
      value: /v1
      type: Prefix

  hpa:
    min_replicas: 1
    max_replicas: 10
    target:
      avg:
        memory: 50
        cpu: 50

  env:
    name: dev
    inspect_beans: 
      enabled: false

totem-food-payment-service:
  replicaCount: 1

  image:
    repository: jeffersoncleyson/totem-food-payment-service
    tag: "v1.0.2"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  loadBalancer:
    totem_food:
      createPublicLB: false

  secrets:
    database:
      url: jdbc:mysql://totem-food-service.aws.us-east-1.rds.amazonaws.com:3306/db_payment?createDatabaseIfNotExist=true
      username: root
      password: root
    payment:
      gateway:
        url: https://api.mercadopago.com
        callback: https://aws.lb/callback
        store_id: POSTOTEM001
        store_user_id: "XX3154YY0ZZ"
        store_token_id: "Bearer TEST-TOKEN"
  
  config:
    payment_topic: payment-topic
    payment_create_queue: create-payment-queue
    email_topic: email-topic

  ## https://towardsdatascience.com/how-to-set-up-ingress-controller-in-aws-eks-d745d9107307
  ingress:
    path:
      value: /v1
      type: Prefix

  hpa:
    min_replicas: 1
    max_replicas: 10
    target:
      avg:
        memory: 50
        cpu: 50

  env:
    name: dev
    inspect_beans: 
      enabled: false


totem-food-order-service:
  replicaCount: 1

  image:
    repository: jeffersoncleyson/totem-food-order-service
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  loadBalancer:
    totem_food:
      createPublicLB: false

  secrets:
    database:
      uri: mongodb+srv://admin:admin@cluster0.xyz.mongodb.net/totem-food-order?authSource=admin

  config:
    payment_topic: payment-topic
    payment_queue_update_order: payment-update-order-queue

  ## https://towardsdatascience.com/how-to-set-up-ingress-controller-in-aws-eks-d745d9107307
  ingress:
    path:
      value: /v1
      type: Prefix

  hpa:
    min_replicas: 1
    max_replicas: 10
    target:
      avg:
        memory: 50
        cpu: 50

  env:
    name: dev
    inspect_beans: 
      enabled: false


totem-food-email-service:
  replicaCount: 1

  image:
    repository: jeffersoncleyson/totem-food-email-service
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  secrets:
    email:
      host: mailhog-mailhog-service.totem-apps.svc.cluster.local
      port: 1025
      username: username
      password: password
      auth:
        enabled: false
      tls:
        enabled: false
      email: contato@totem.food.service.com.br
  
  config:
    email_queue: email-queue

  hpa:
    min_replicas: 1
    max_replicas: 10
    target:
      avg:
        memory: 50
        cpu: 50

  env:
    name: dev
    inspect_beans: 
      enabled: false

