apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tfc-svc-lb-private
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfc
    app.kubernetes.io/name: {{ .Release.Name }}-tfc
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfc
    app.kubernetes.io/name: {{ .Release.Name }}-tfc
  type: LoadBalancer