replicaCount: 1

image:
  repository: jeffersoncleyson/totem-food-service
  tag: "temporary"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

loadBalancer:
  totem_food:
    createPublicLB: false

secrets:
  database:
    uri: mongodb://root:qwe123@mongo-mongodb-service.totem-apps.svc.cluster.local:27017/totem-food?authSource=admin

config:
  payment_topic: payment-topic
  payment_queue_update_order: payment-update-order-queue
  
## https://towardsdatascience.com/how-to-set-up-ingress-controller-in-aws-eks-d745d9107307
ingress:
  path:
    value: /v1
    type: Prefix

hpa:
  min_replicas: 1
  max_replicas: 10
  target:
    avg:
      memory: 50
      cpu: 50

env:
  name: dev
  inspect_beans: 
    enabled: false
