apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-totem-food-database-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-totem-food
    app.kubernetes.io/name: {{ .Release.Name }}-totem-food
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: {{ .Values.secrets.database.uri }}