replicaCount: 1

image:
  repository: jeffersoncleyson/tfc-svc
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

loadBalancer:
  totem_food:
    createPublicLB: false

secrets:
  cognito:
    userPoolId: userPoolId
    clientId: clientId
    clientSecret: clientSecret

## https://towardsdatascience.com/how-to-set-up-ingress-controller-in-aws-eks-d745d9107307
ingress:
  path:
    value: /v1
    type: Prefix

hpa:
  min_replicas: 1
  max_replicas: 10
  target:
    avg:
      memory: 50
      cpu: 50

env:
  name: dev
  inspect_beans: 
    enabled: false
