apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tfp-database-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfp
    app.kubernetes.io/name: {{ .Release.Name }}-tfp
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: {{ .Values.secrets.database.uri }}