apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tfp-payment-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfp
    app.kubernetes.io/name: {{ .Release.Name }}-tfp
type: Opaque
stringData:
  PAYMENT_GATEWAY_URL: {{ .Values.secrets.payment.gateway.url }}
  PAYMENT_CALLBACK_URL: {{ .Values.secrets.payment.gateway.callback }}
  STORE_ID: {{ .Values.secrets.payment.gateway.store_id }}
  STORE_USER_ID: {{ .Values.secrets.payment.gateway.store_user_id | quote }}
  STORE_TOKEN: {{ .Values.secrets.payment.gateway.store_token_id }}