apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfp
    app.kubernetes.io/name: {{ .Release.Name }}-tfp
  name: {{ .Release.Name }}-tfp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}-tfp
      app.kubernetes.io/name: {{ .Release.Name }}-tfp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tfp
        app.kubernetes.io/instance: {{ .Release.Name }}-tfp
        app.kubernetes.io/name: {{ .Release.Name }}-tfp
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-tfp-database-secrets
          - secretRef:
              name: {{ .Release.Name }}-tfp-payment-secrets
          - configMapRef:
              name: {{ .Release.Name }}-tfp-internal-cfg
          - configMapRef:
              name: {{ .Release.Name }}-tfp-sqs-sns-cfg
        ports:
          - containerPort: {{ .Values.service.port }}
            name: http
            protocol: TCP
          - containerPort: 8787
            name: debug
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
