apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tfp-svc-lb-private
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfp
    app.kubernetes.io/name: {{ .Release.Name }}-tfp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfp
    app.kubernetes.io/name: {{ .Release.Name }}-tfp
  type: LoadBalancer