apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tfp-sqs-sns-cfg
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfc
    app.kubernetes.io/name: {{ .Release.Name }}-tfc
data:
  PAYMENT_TOPIC: {{ .Values.config.payment_topic | quote }}
  EMAIL_TOPIC: {{ .Values.config.email_topic | quote }}
  PAYMENT_CREATE_QUEUE: {{ .Values.config.payment_create_queue | quote }}