apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tfp-database-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfp
    app.kubernetes.io/name: {{ .Release.Name }}-tfp
type: Opaque
stringData:
  PAYMENT_DB_URL: {{ .Values.secrets.database.url }}
  PAYMENT_DB_USERNAME: {{ .Values.secrets.database.username }}
  PAYMENT_DB_PASSWORD: {{ .Values.secrets.database.password }}