apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tfo-internal-cfg
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfc
    app.kubernetes.io/name: {{ .Release.Name }}-tfc
data:
  MS_INTERNAL_CUSTOMER: "http://{{ .Release.Name }}-tfc.{{ .Release.Namespace }}.svc.cluster.local:8080"
  MS_INTERNAL_PAYMENT: "http://{{ .Release.Name }}-tfp.{{ .Release.Namespace }}.svc.cluster.local:8080"
  MS_INTERNAL_ORDER: "http://{{ .Release.Name }}-tfo.{{ .Release.Namespace }}.svc.cluster.local:8080"
  INSPECT_BEANS: "{{ .Values.env.inspect_beans.enabled }}"
  SERVER_PORT: {{ .Values.service.port | quote }}