apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tfo-sns-sqs-cfg
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfc
    app.kubernetes.io/name: {{ .Release.Name }}-tfc
data:
  PAYMENT_TOPIC: {{ .Values.config.payment_topic | quote }}
  PAYMENT_QUEUE_UPDATE_ORDER: {{ .Values.config.payment_queue_update_order | quote }}