apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tfo-email-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfo
    app.kubernetes.io/name: {{ .Release.Name }}-tfo
type: Opaque
stringData:
  SMTP_HOST: {{ .Values.secrets.email.host }}
  SMTP_PORT: "{{ .Values.secrets.email.port }}"
  SMTP_USERNAME: {{ .Values.secrets.email.username }}
  SMTP_PASSWORD: {{ .Values.secrets.email.password }}
  SMTP_AUTH_ENABLED: "{{ .Values.secrets.email.auth.enabled }}"
  SMTP_TLS_ENABLED: "{{ .Values.secrets.email.tls.enabled }}"
  SMTP_EMAIL: {{ .Values.secrets.email.email }}