apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tfo-svc
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfo
    app.kubernetes.io/name: {{ .Release.Name }}-tfo
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-tfo
    app.kubernetes.io/name: {{ .Release.Name }}-tfo
  type: ClusterIP
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
